In [1]:
from google.colab import files
uploaded=files.upload()

Saving hamoye.csv to hamoye.csv

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("hamoye.csv")

In [4]:
df.shape

(44812, 95)

In [6]:
df.head()

  Country Name Country Code  ... 2049 [YR2049]  2050 [YR2050]
0  Afghanistan          AFG  ...     44.471497      43.992485
1  Afghanistan          AFG  ...      7.935899       8.175734
2  Afghanistan          AFG  ...     36.535598      35.816751
3  Afghanistan          AFG  ...           NaN  430000.000000
4  Afghanistan          AFG  ...           NaN  452000.000000

[5 rows x 95 columns]